### ISSUE TITLE
progressSamples incorrect when doesAllowStretch = true and zoomed in

### ISSUE THREAD

**Issue by nickcastel50** [fulldecent/FDWaveformView#85] opened 2017-04-08 18:05 UTC
When you enable doesAllowStretch and zoom in, the progressSamples value is incorrect in relation to where you click on the wave form. It seems to always calculate progress samples based on the zoomed out waveform. Let me know if you need more information and I will try to provide it.

**Comment by fulldecent** [comment] 2017-04-09 05:05
Thank you, yes I can confirm this is broken now.

**Comment by nickcastel50** [comment] 2017-04-10 21:46
Any ideas on a fix? From the example images it seems like it was working before.

**Comment by fulldecent** [comment] 2017-04-14 18:36
Sorry, I haven't been able to figure this out. But here is what I was able to find:

* Zoom out all the way. Then zoom in exactly half way and pan right (so the first half of the waveform is shown.
* Now click on the very right side. This will set progress to 50%.
* Then pan left all the way

As expected, the progress is just at the very left of the screen.

However, unexpectedly, the end of the waveform is also at the very left of the screen. Therefore, effectively, the progress is set at the end of the waveform.

This helps to illustrate that the root cause is the waveform is being shown in three halves. The first and second half are just off to the left of the screen (and each half occupies the size of one screen). However the third half is occupying all the visible space and it is showing a flatline waveform (i.e. nothing).

Instead, at this zoom level there should be NO extra space to the right of the waveform.

**Comment by nickcastel50** [comment] 2017-05-03 03:39
I've made some progress on this. As I said in the original post, it seemed to be calculating progressSamples based on the zoomed out waveform. The reason is because, in handlePanGesture, we handle scrubbing like so:

```
else if doesAllowScrubbing {
    let rangeSamples = CGFloat(zoomEndSamples - zoomStartSamples)
    progressSamples = Int(CGFloat(zoomStartSamples) + rangeSamples * recognizer.location(in: self).x / bounds.width)
}
```

The problem with this is, when you zoom in towards the end of the waveform, the frame X value for imageView and highlightedImage is set to a negative value (to preserve the waveform off screen) and the width is increased to make up the difference, but the waveView frame never changes. So to calculate progressSamples properly, you should do this:

```
else if doesAllowScrubbing {
    let point = recognizer.location(in: self.imageView)
    let rangeSamples = CGFloat(zoomEndSamples - zoomStartSamples)
    progressSamples = Int(CGFloat(zoomStartSamples) + rangeSamples * point.x / bounds.width)
}
```

That will give you a correct progressSamples value in relation to where you pan on the waveform. The only issue with this is that it doesn't solve the issue of there being space at the right of the waveform, so as a quick fix you can cap the progressSamples to totalSamples and then you won't be able to pan past the end of the waveform.

This is an adequate fix for my purposes, but if there's anything wrong with this implementation for your vision of the library let me know and maybe I can help with it. Great library by the way 👍

**Comment by fulldecent** [comment] 2017-05-03 17:26
Just finished merge of #80, confirmed still an issue after that.

**Comment by fulldecent** [comment] 2017-05-03 17:31
Thanks for your help here. Wow, I didn't realize it was setting it wrong too in addition to reading it wrong.

This approach:

```
    let pointInImageView = recognizer.location(in: self.imageView)
    let rangeSamples = CGFloat(zoomEndSamples - zoomStartSamples)
    progressSamples = Int(CGFloat(zoomStartSamples) + rangeSamples * pointInImageView.x / bounds.width)
```

seems wrong. The the point in the image view should correspond to the rendered range and the point in the parent view should correspond to the zoom range.

**Comment by nickcastel50** [comment] 2017-05-03 18:01
@fulldecent Hmm, can you explain that a bit more? I seem to be able to calculate a correct progressSamples value by using the X coordinate from imageView, although like I said if panning past the waveform progressSamples >  totalSamples. I did notice issue #83 is still present with this method, so you may be right that this isn't the best fix.

**Comment by fulldecent** [comment] 2019-04-09 03:41
This issue is fixed in the latest release from today. Thanks to some hard work by @reedom.

Closing. If I'm closing incorrectly, please reopen.

**Closed by fulldecent** 2019-04-09 03:41 UTC
Labels: bug
