### ISSUE TITLE
Scroll change the scale 

### ISSUE THREAD

**Issue by trevor-sonic** [fulldecent/FDWaveformView#83] opened 2017-03-20 11:07 UTC
Hi,
I've noticed that after some zooming (let's say 2x) scrolling the image shows noticeable with scale changes. Image is looking narrower. 
It is more noticeable when scrubbing. Blue selected area change its position with scroll.
Any idea?
Thanks 
Below images before and after scrolling to left.
First image we see 4 picks of the beat, in second 5th beat is shown because of some calculation issue (I guess)

<img width="367" alt="before scroling" src="https://cloud.githubusercontent.com/assets/307560/24097297/1ccd244e-0d5d-11e7-90e3-fba89ba5c121.png">
<img width="358" alt="after scrolling" src="https://cloud.githubusercontent.com/assets/307560/24097298/1cf2ccb2-0d5d-11e7-8993-556bc56db99b.png">

**Comment by fulldecent** [comment] 2017-03-23 02:59
Thank you, yes this looks like an error. I am trying to investigate and reproduce this issue.

**Comment by fulldecent** [comment] 2017-04-14 18:54
Hello @trevor-sonic I have added details in #85 and a test case.

I'm not quite sure how to fix it yet. Closing this issue to focus discussion there.

**Closed by fulldecent** 2017-04-14 18:54 UTC
