### ISSUE TITLE
Not drawing (Pod)

### ISSUE THREAD

**Issue by rafaelc0sta** [fulldecent/FDWaveformView#70] opened 2016-10-05 18:10 UTC
Updated the pod to version 2.0.0 and it doesn't draw. Previous version worked fine.

**Comment by jboegeholz** [comment] 2017-03-28 17:58
Do You get an error message in the console?

**Comment by fulldecent** [comment] 2017-04-14 19:28
I cannot reproduce. Closing now to clean up. Please reopen if you are still having the problem on the latest version.

**Closed by fulldecent** 2017-04-14 19:28 UTC
